from auth_service.src.core.exceptions import exceptions

__all__ = ["exceptions"]
